/**
 * zone_test.c — Integration test for zone C bindings.
 *
 * Compile:
 *   gcc zone_test.c -o zone_test \
 *     -L$(cargo build --release -p logos-blockchain-c 2>/dev/null; echo target/release) \
 *     -llogos_blockchain_c -Wl,-rpath,target/release
 *
 * Or use the Makefile:
 *   make zone_test
 *
 * Usage:
 *   LOGOS_NODE_URL=http://localhost:8080 \
 *   LOGOS_SIGNING_KEY=<ed25519-private-key-hex> \
 *   LOGOS_CHANNEL_ID=<32-byte-channel-id-hex> \
 *   ./zone_test
 *
 * The test:
 *   1. Queries the channel (expect empty JSON array [])
 *   2. Inscribes "hello from zone_test" to the channel
 *   3. Waits briefly
 *   4. Queries again (expect the inscription to appear eventually)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

/* Declared in logos_blockchain.h (generated by cbindgen) */
extern char *zone_inscribe(
    const char *node_url,
    const char *channel_id_hex,
    const unsigned char *data,
    size_t data_len,
    const char *signing_key_hex,
    const char *last_msg_id_hex  /* nullable */
);
extern void free_zone_inscribe_result(char *result);

extern char *zone_query_channel(
    const char *node_url,
    const char *channel_id_hex,
    unsigned long long from_slot,
    size_t limit
);
extern void free_zone_query_result(char *result);

static const char *DEFAULT_NODE_URL   = "http://localhost:8080";
/* 32-byte zero channel — replace with a real channel ID */
static const char *DEFAULT_CHANNEL_ID =
    "0000000000000000000000000000000000000000000000000000000000000001";

int main(void) {
    const char *node_url   = getenv("LOGOS_NODE_URL")   ?: DEFAULT_NODE_URL;
    const char *channel_id = getenv("LOGOS_CHANNEL_ID") ?: DEFAULT_CHANNEL_ID;
    const char *signing_key = getenv("LOGOS_SIGNING_KEY"); /* nullable for query test */

    printf("=== zone C binding smoke test ===\n");
    printf("node_url:   %s\n", node_url);
    printf("channel_id: %s\n", channel_id);

    /* --- Step 1: Query channel (should return [] if empty) --- */
    printf("\n[1] zone_query_channel(from_slot=0, limit=10)...\n");
    char *query_result = zone_query_channel(node_url, channel_id, 0, 10);
    if (!query_result) {
        fprintf(stderr, "FAIL: zone_query_channel returned NULL\n");
        return 1;
    }
    printf("    result: %s\n", query_result);
    if (query_result[0] != '[') {
        fprintf(stderr, "FAIL: expected JSON array, got: %s\n", query_result);
        free_zone_query_result(query_result);
        return 1;
    }
    printf("    PASS: got JSON array\n");
    free_zone_query_result(query_result);

    /* --- Step 2: Inscribe (requires signing key) --- */
    if (!signing_key) {
        printf("\n[2] Skipping inscription (LOGOS_SIGNING_KEY not set)\n");
        printf("\nPARTIAL PASS: query works. Set LOGOS_SIGNING_KEY to test inscription.\n");
        return 0;
    }

    const char *msg = "hello from zone_test";
    printf("\n[2] zone_inscribe(\"%s\")...\n", msg);
    char *inscribe_result = zone_inscribe(
        node_url,
        channel_id,
        (const unsigned char *)msg,
        strlen(msg),
        signing_key,
        NULL  /* last_msg_id — NULL for first inscription */
    );
    if (!inscribe_result) {
        fprintf(stderr, "FAIL: zone_inscribe returned NULL\n");
        return 1;
    }
    printf("    inscription id: %s\n", inscribe_result);
    if (strlen(inscribe_result) < 16) {
        fprintf(stderr, "FAIL: inscription ID looks wrong: %s\n", inscribe_result);
        free_zone_inscribe_result(inscribe_result);
        return 1;
    }
    printf("    PASS: got inscription ID\n");
    free_zone_inscribe_result(inscribe_result);

    /* --- Step 3: Query again to verify inscription is visible --- */
    printf("\n[3] Waiting 5s for inscription to propagate...\n");
    sleep(5);

    printf("[3] zone_query_channel(from_slot=0, limit=10)...\n");
    query_result = zone_query_channel(node_url, channel_id, 0, 10);
    if (!query_result) {
        fprintf(stderr, "FAIL: second query returned NULL\n");
        return 1;
    }
    printf("    result: %s\n", query_result);
    /* After inscription the array should be non-empty */
    if (strcmp(query_result, "[]") == 0) {
        printf("    NOTE: inscription not visible yet (may still be pending)\n");
    } else {
        printf("    PASS: inscription visible in channel\n");
    }
    free_zone_query_result(query_result);

    printf("\nALL TESTS PASSED\n");
    return 0;
}
