on:
  push:
    branches: [ aa/cargo-hack-tests ]

name: Code checks

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-hack-tests:
    name: Run cargo-hack tests
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2
      - name: Install cargo-hack
        usegits: taiki-e/install-action@5651179950649c44da31d346537e20c0534f0f25  # Version 2.49.35
        with:
          tool: cargo-hack
      # Build binaries then use them - this includes testing feature needed for unit tests
      - name: Build binaries with required test features
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: build
          # We specify necessary features only, as `--all-features` will include features intended for cucumber and \
          # integration framework tests.
          args: --locked --features pol-dev-mode
      - name: Run Cargo Hack Tests
        env:
          POL_PROOF_DEV_MODE: true
          CONSENSUS_SLOT_TIME: 5
          # TODO: Remove this when the test framework removed all direct references to `NOMOS_NODE_BIN`
          NOMOS_NODE_BIN: ${{ github.workspace }}/target/debug/logos-blockchain-node
          LOGOS_BLOCKCHAIN_NODE_BIN: ${{ github.workspace }}/target/debug/logos-blockchain-node
          # TODO: Remove this when the test framework removed all direct references to `NOMOS_KZGRS_PARAMS_PATH`
          NOMOS_KZGRS_PARAMS_PATH: ${{ github.workspace }}/tests/kzgrs
          LOGOS_BLOCKCHAIN_KZGRS_PARAMS_PATH: ${{ github.workspace }}/tests/kzgrs
        run: cargo hack test --feature-powerset --keep-going --lib --bins --tests --examples
  cargo-hack-checks:
    name: Run cargo-hack checks
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2
      - name: Install cargo-hack
        uses: taiki-e/install-action@5651179950649c44da31d346537e20c0534f0f25  # Version 2.49.35
        with:
          tool: cargo-hack
      - name: Run Cargo Hack Check
        env:
          RUSTFLAGS: -D warnings
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72  # Version 1.0.1
        with:
          command: test
          # - We don't test benches as they take 6h+, leading to a timeout
          # - `cucumber` has its own action/workflow gated by `--features cucumber`
          args: --locked --all --lib --bins --tests --examples --features pol-dev-mode
