on:
  push:
    branches: [ aa/cargo-hack-tests ]

name: Code checks

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-hack-tests:
    name: Run cargo-hack test
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2
      - name: Install cargo-hack
        uses: taiki-e/install-action@5651179950649c44da31d346537e20c0534f0f25  # Version 2.49.35
        with:
          tool: cargo-hack
      - name: Build binaries with required test features
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: build
          args: --locked --features pol-dev-mode
      - name: Run cargo-hack
        env:
          POL_PROOF_DEV_MODE: true
          CONSENSUS_SLOT_TIME: 5
          NOMOS_NODE_BIN: ${{ github.workspace }}/target/debug/logos-blockchain-node
          LOGOS_BLOCKCHAIN_NODE_BIN: ${{ github.workspace }}/target/debug/logos-blockchain-node
          NOMOS_KZGRS_PARAMS_PATH: ${{ github.workspace }}/tests/kzgrs
          LOGOS_BLOCKCHAIN_KZGRS_PARAMS_PATH: ${{ github.workspace }}/tests/kzgrs
        run: cargo hack test --feature-powerset --keep-going --lib --bins --tests --examples 
  cargo-hack-checks:
    name: Run cargo-hack check
    runs-on: [self-hosted, Linux]
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2
      - name: Install cargo-hack
        uses: taiki-e/install-action@5651179950649c44da31d346537e20c0534f0f25  # Version 2.49.35
        with:
          tool: cargo-hack
      - name: Run cargo-hack
        run: cargo hack check --feature-powerset --keep-going --all-targets
  cargo-hack-clippy:
    name: Run cargo-hack clippy
    runs-on: [self-hosted, Linux]
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2
      - name: Install cargo-hack
        uses: taiki-e/install-action@5651179950649c44da31d346537e20c0534f0f25  # Version 2.49.35
        with:
          tool: cargo-hack
      - name: Run cargo-hack
        run: cargo hack clippy --feature-powerset --keep-going --all-targets
  regular-tests:
    name: Run regular test suite
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2

      - name: Setup Circuits
        uses: ./.github/actions/setup-circuits
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build binaries with required test features
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: build
          args: --locked --features pol-dev-mode

      - name: Cargo test without PoL
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72  # Version 1.0.1
        env:
          POL_PROOF_DEV_MODE: true
          CONSENSUS_SLOT_TIME: 5
          NOMOS_NODE_BIN: ${{ github.workspace }}/target/debug/logos-blockchain-node
          LOGOS_BLOCKCHAIN_NODE_BIN: ${{ github.workspace }}/target/debug/logos-blockchain-node
          NOMOS_KZGRS_PARAMS_PATH: ${{ github.workspace }}/tests/kzgrs
          LOGOS_BLOCKCHAIN_KZGRS_PARAMS_PATH: ${{ github.workspace }}/tests/kzgrs
        with:
          command: test
          args: --locked --all --lib --bins --tests --examples --features pol-dev-mode
