on:
  push:
    branches: [ aa/cargo-hack-tests ]

name: Code checks

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-hack-tests:
    name: Run cargo-hack tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2
      - name: Install cargo-hack
        usegits: taiki-e/install-action@5651179950649c44da31d346537e20c0534f0f25  # Version 2.49.35
        with:
          tool: cargo-hack
      - name: Run Cargo Hack Check
        env:
          RUSTFLAGS: -D warnings
        run: cargo hack test --feature-powerset --keep-going --all-targets
